// This file was auto-generated by ML.NET Model Builder. 

using System;
using ML_NET_ML.Model;

namespace ML_NET_ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            
        }
    }
}
 
